config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users do
    resources :groups
    resources :expenditures
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expenditure.rb
class Expenditure < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :groups, dependent: :destroy
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :expenditures, dependent: :destroy

  validates :name, length: { in: 3..20 }
  validates :icon, presence: true
end

app/models/group_expenditure.rb
class GroupExpenditure < ApplicationRecord
  belongs_to :group
  belongs_to :expenditure
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :confirmable, :rememberable, :validatable
  has_many :expenditures
  has_many :groups

  validates :email, uniqueness: true, length: { in: 5..30 }
  validates :name, uniqueness: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/expenditures_controller.rb
class ExpendituresController < ApplicationController
  before_action :authenticate_user!

  # GET /expenditures or /expenditures.json
  def index
    @user = current_user
    @group = Group.find(params[:group_id])
    @expenditures = Expenditure.where(user_id: @user.id, group_id: @group.id)
    @total = @expenditures.sum(:amount)
  end

  def new
    @user = current_user
    @expenditure = Expenditure.new
    @group = Group.all.where(user_id: @user.id).map { |g| [g.name, g.id] }
  end

  def create
    @expenditure = Expenditure.new(expenditure_params)
    @expenditure.user_id = current_user.id

    respond_to do |format|
      if @expenditure.save
        format.html do
          redirect_to user_group_url(current_user.id, @expenditure.group_id),
                      notice: 'Expenditure was successfully created.'
        end
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expenditure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenditures/1 or /expenditures/1.json
  def destroy
    @expenditure.destroy

    respond_to do |format|
      format.html { redirect_to expenditures_url, notice: 'Expenditure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def expenditure_params
    params.require(:expenditure).permit!
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: %i[show edit update destroy]

  def index
    @user = User.find(params[:user_id])
    @groups = Group.where(user_id: @user.id)
    @expenditures = Expenditure.where(group_id: @groups.ids)
  end

  def show
    # @user = current_user.id
    # @group = Group.find_by(id: params[:id])
    @expenditures = Expenditure.all.where(group_id: @group.id)
  end

  def new
    @user = User.find(params[:user_id])
    @group = Group.new
  end

  def create
    @user = User.find(params[:user_id])
    @group = Group.new(group_params)
    @group.user_id = @user.id

    respond_to do |format|
      if @group.save
        format.html { redirect_to user_groups_path(@user), notice: 'Group was successfully created.' }
        format.json { render :index, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit!
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    user_groups_path(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    user_groups_path(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index; end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.fetch(:user, {})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenditures_helper.rb
module ExpendituresHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def total_amount_helper(expenditures)
    expenditures.reduce(0) { |sum, expenditure| sum + expenditure.amount }
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/expenditures/_expenditure.html.erb
<div id="<%= dom_id expenditure %>">

<div class="expense-display">
  <span class="expense-name"><%= expenditure.name %></span>
  <span class="expense-amount"><%= number_to_currency(expenditure.amount) %></span> 
</div>
</div>

app/views/expenditures/_form.html.erb
<%= form_with model: [@user, @expenditure] do |form| %>

  <div>
    <%= form.text_field :name, placeholder: "Expense Name" %>
  </div>

  <div>
    <%= form.number_field :amount, placeholder: "Expense Amount" %>
  </div>
  <div class="select">
  <%= form.select(:group_id, @group) %>
  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/expenditures/edit.html.erb
<h1>Editing expenditure</h1>

<%= render "form", expenditure: @expenditure %>

<br>

<div>
  <%= link_to "Show this expenditure", @expenditure %> |
  <%= link_to "Back to expenditures", expenditures_path %>
</div>

app/views/expenditures/index.html.erb
<div id="expenditures">

<h1> <%= link_to user_groups_path do %>
 <i class="fa-solid fa-chevron-left" style="color: #3778c2; padding-left: 22px"> </i>
 <% end %>
 </h1>
 <div class="all-expense">
 <div class="total"> <span class="expense">Expenditures </span>
 <span> <%= number_to_currency(@total) %> </span>
 </div>
  <% @expenditures.each do |expenditure| %>
  <%= render expenditure %>
  <% end %>
    <div class="new-form"> 
   <span> <%= link_to 'New Expenditure', new_user_group_expenditure_path %> </span>
  </div>
  </div>
</div>

app/views/expenditures/new.html.erb
<h1> <%= link_to user_groups_path do %>
 <i class="fa-solid fa-chevron-left" style="color: #3778c2; padding-left: 22px"> </i>
 <% end %>
 </h1>
<%= render "form", expenditure: @expenditure %>

app/views/expenditures/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @expenditure %>

<div>
  <%= link_to "Edit this expenditure", edit_expenditure_path(@expenditure) %> |
  <%= link_to "Back to expenditures", expenditures_path %>
  <%= button_to "Destroy this expenditure", @expenditure, method: :delete %>
</div>
<%# <%= @expenditure.name %>
<%# <% @groups.each do |group| %>
  <%# <%= group.name %> 
<%# <% end %>

app/views/groups/_form.html.erb
<div class="form">
<%= form_with model: [@user, @group] do |form| %>

  <div>
    <%= form.text_field :name, placeholder: "Group Name" %>
  </div>

  <div>
    <%= form.text_field :icon, placeholder: "Image Link" %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>">
<div class="group-display">
<div class="group-list">
  <div class="img"><img src="<%= group.icon %>"> </div>
  <div class="group-name"><%= link_to group.name, user_group_path(id: group.id, user_id: group.user_id) %>
  <span><%= total_amount_helper(Expenditure.all.where(group_id: group.id)) %> <span>  </div>
  </div>
  <span class="date"><%= group.created_at.to_date %></span>
</div>
</div>

app/views/groups/index.html.erb
<div class="header-div">
   <h1 class="header"> Expenditures </h1>
</div>
<div id="groups" class="container">
<% if user_signed_in? %>
 <div class="grouping">
 <%= button_to 'Sign Out', destroy_user_session_path, method: :delete %>

 <div class="total row">
    <h3 col-6> Expenditures</h3>
    <h3 col-6><%= number_to_currency(@expenditures.sum(&:amount)) %> </h3>
 </div>
 
  <% @groups.each do |group| %>
  <%= render group %>
  <% end %> 
  <div class="new-form"> 
   <span> <%= link_to 'New Group', new_user_group_path %> </span>
  </div>
</div>
 <% else %>
 <span class="sign-link"> <strong> <%= link_to 'Sign In', new_user_session_path %> </span>
 <span class="sign-link"><strong> <%= link_to 'Sign Up', new_user_registration_path %> </strong> </span> 
 <% end %> 
</div>

app/views/groups/new.html.erb
<h1> <%= link_to user_groups_path do %>
 <i class="fa-solid fa-chevron-left" style="color: #3778c2; padding-left: 22px"> </i>
 <% end %>
 </h1>
<%= render "form", group: @group %>

app/views/groups/show.html.erb
<div id="expenditures">
<div class="header-div">
   <h1 class="header"> Transactions </h1>
</div>
  <h1> <%= link_to user_groups_path do %>
  <i class="fa-solid fa-chevron-left" style="color: #3778c2; padding-left: 22px"> </i>
 <% end %>
  </h1>
 <div class="all-expense">
 <div class="total"> <span class="expense">Total </span>
  <span> <%= number_to_currency(@expenditures.sum(:amount)) %> </span>
 </div>
  <% @expenditures.each do |expenditure| %>
  <%= render expenditure %>
  <% end %>
    <div class="new-form"> 
   <span> <%= link_to 'New Expenditure', new_user_expenditure_path %> </span>
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

     <script src="https://kit.fontawesome.com/b331332bf9.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>

  <body>
 <nav class="sticky-top navbar-dark bg-dark">
      <ul class="nav-list d-flex align-items-center justify-content-between mb-0">
        <li class="navbar-brand"> <%= link_to "👤 BO-JET", root_path, class: "home-budget" %> </li>
        <div class="d-flex align-items-center justify-content-between">
          <% if user_signed_in? %>
            <li class="navbar-brand fs-6"> <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-outline-secondary " %></li>
          <% else %>
            <li class="navbar-brand fs-6"> <%= link_to "Sign In", new_user_session_path, method: :delete, class: "btn btn-outline-secondary " %></li>
            <li class="navbar-brand fs-6"> <%= link_to "Sign Up", new_user_registration_path, method: :delete, class: "btn btn-outline-secondary " %></li>
          <% end %>
        </div>
      </ul>
    </nav>
     <% flash.each do |name, msg| -%>
      <div class="alert alert-success" role="alert">
        <%= msg %>
      </div>
    <% end -%>
    <div class="container" style="padding-bottom:50px">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
</div>

app/views/users/index.html.erb
<div id="users" class="user container">
<div class="row">
      <h1 class="appname col-12"> Bo-jet App </h1>
      <div class="signin col-12"> <strong> <%= link_to 'Sign In', new_user_session_path %> </strong> </div> 
      <div class="signout col-12"> <strong> <%= link_to 'Sign Up', new_user_registration_path %> </strong> </div>
</div>
</div>